<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 static/models/littlescene.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations, OrbitControls } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/littlescene.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T.PerspectiveCamera makeDefault position={[0,2,2]}>
  <OrbitControls enableZoom={false}/>
</T.PerspectiveCamera>

<T.DirectionalLight color="white" position={[0,2,5]} intensity={2} />
<!-- <T.PointLight color="yellow" position={[0.72,0.25, -0.1]} intensity={0.5} /> -->
<!-- <T.PointLight color="red" position={[1,1,0]} intensity={0.5}/>
<T.PointLight color="orange" position={[-1,0.5,0]} intensity={0.5}/>
<T.PointLight color="green" position={[1,0,0]} intensity={0.5}/>
<T.PointLight color="blue" position={[0,1,0]} intensity={0.5}/>
<T.PointLight color="purple" position={[-2,0.5,0]} intensity={0.5}/> -->

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="66c381b9888c47619f56531729313407fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <T.Group name="RootNode">
            <T.Group name="PUBG_dragon_ball" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <T.Mesh
                name="PUBG_dragon_ball_VehBody_0"
                geometry={gltf.nodes.PUBG_dragon_ball_VehBody_0.geometry}
                material={gltf.materials.VehBody}
                position={[-0.06, -0.32, 0.06]}
                rotation={[-0.01, -0.01, -0.9]}
                scale={0.16}
              />
              <T.Mesh
                name="PUBG_dragon_ball_VehGlass_0"
                geometry={gltf.nodes.PUBG_dragon_ball_VehGlass_0.geometry}
                material={gltf.materials.VehGlass}
                position={[-0.06, -0.32, 0.08]}
                rotation={[-0.02, 0, -0.9]}
                scale={0.16}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group name="Sketchfab_model001" position={[-0.23, 0.15, -0.08]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <T.Group name="Root">
          <T.Group name="Cylinder" scale={[1, 1, 6.69]}>
            <T.Mesh
              name="Cylinder_0"
              geometry={gltf.nodes.Cylinder_0.geometry}
              material={gltf.materials.tree_wood}
              position={[-6.87, -10.71, -1.24]}
            />
            <T.Mesh
              name="Cylinder_0001"
              geometry={gltf.nodes.Cylinder_0001.geometry}
              material={gltf.materials.tree_wood}
              position={[28.57, 6.09, -1.21]}
              rotation={[0, 0, 1.09]}
              scale={0.88}
            />
          </T.Group>
          <T.Group name="Icosphere" position={[0.03, 1.99, 17.45]} scale={2.44}>
            <T.Mesh
              name="Icosphere_0"
              geometry={gltf.nodes.Icosphere_0.geometry}
              material={gltf.materials['leaf_green.003']}
              position={[-2.81, -4.38, -2.11]}
            />
          </T.Group>
          <T.Group name="Icosphere001" position={[-12.06, 11.58, 15.39]} scale={2.44}>
            <T.Mesh
              name="Icosphere001_0"
              geometry={gltf.nodes.Icosphere001_0.geometry}
              material={gltf.materials['leaf_green.004']}
              position={[-2.81, -4.38, -2.11]}
            />
          </T.Group>
          <T.Group name="Icosphere002" position={[-12.83, -4.37, 18.68]} scale={2.44}>
            <T.Mesh
              name="Icosphere002_0"
              geometry={gltf.nodes.Icosphere002_0.geometry}
              material={gltf.materials['leaf_green.001']}
              position={[-2.81, -4.38, -3.39]}
            />
          </T.Group>
          <T.Group name="Icosphere003" position={[13.32, 3.81, 17.45]} scale={2.44}>
            <T.Mesh
              name="Icosphere003_0"
              geometry={gltf.nodes.Icosphere003_0.geometry}
              material={gltf.materials.leaf_green}
              position={[9.72, 3, -2.7]}
              rotation={[0, 0, 2.77]}
            />
            <T.Mesh
              name="Icosphere003_0001"
              geometry={gltf.nodes.Icosphere003_0001.geometry}
              material={gltf.materials.leaf_green}
              position={[7.24, 5.82, -3.05]}
              rotation={[0, 0, 1.09]}
              scale={0.88}
            />
          </T.Group>
          <T.Group name="Icosphere004" position={[5.02, -8, 13.47]} scale={2.44}>
            <T.Mesh
              name="Icosphere004_0"
              geometry={gltf.nodes.Icosphere004_0.geometry}
              material={gltf.materials['leaf_green.002']}
              position={[-2.81, -4.38, -2.72]}
            />
          </T.Group>
          <T.Group name="Icosphere005" position={[1.94, 12.6, 14.49]} scale={2.44}>
            <T.Mesh
              name="Icosphere005_0"
              geometry={gltf.nodes.Icosphere005_0.geometry}
              material={gltf.materials['leaf_green.005']}
              position={[1.64, -13.3, 0.18]}
            />
          </T.Group>
          <T.Group name="Icosphere006" position={[36.74, 1.63, 15.09]} rotation={[0, 0, -1.68]} scale={2.15}>
            <T.Mesh
              name="Icosphere_0001"
              geometry={gltf.nodes.Icosphere_0001.geometry}
              material={gltf.materials['leaf_green.003']}
              position={[-1.97, -4.76, -2.37]}
              rotation={[0, 0, 2.77]}
            />
          </T.Group>
          <T.Group name="Icosphere007" position={[47.4, 12.45, 15.18]} rotation={[0, 0, -1.68]} scale={2.42}>
            <T.Mesh
              name="Icosphere001_0001"
              geometry={gltf.nodes.Icosphere001_0001.geometry}
              material={gltf.materials['leaf_green.004']}
              position={[5.99, -12.97, -2.89]}
              rotation={[0, 0, 2.77]}
              scale={0.89}
            />
          </T.Group>
          <T.Group name="Icosphere008" position={[31.77, 14.9, 15.35]} rotation={[0, 0, -1.68]} scale={2.42}>
            <T.Mesh
              name="Icosphere002_0001"
              geometry={gltf.nodes.Icosphere002_0001.geometry}
              material={gltf.materials['leaf_green.001']}
              position={[8.68, -1.15, -2.9]}
              rotation={[0, 0, 2.77]}
              scale={0.89}
            />
          </T.Group>
          <T.Group name="Icosphere009" position={[27.54, -1.8, 11.59]} rotation={[0, 0, -1.68]} scale={2.15}>
            <T.Mesh
              name="Icosphere004_0001"
              geometry={gltf.nodes.Icosphere004_0001.geometry}
              material={gltf.materials['leaf_green.002']}
              position={[-4.42, 3.88, -2.37]}
              rotation={[0, 0, 2.77]}
            />
          </T.Group>
          <T.Group name="Icosphere010" position={[45.84, -1.03, 15.61]} rotation={[0, 0, -1.68]} scale={2.15}>
            <T.Mesh
              name="Icosphere005_0001"
              geometry={gltf.nodes.Icosphere005_0001.geometry}
              material={gltf.materials['leaf_green.005']}
              position={[-5.06, -12.86, -3.82]}
              rotation={[0, 0, 2.77]}
            />
          </T.Group>
          <T.Group name="Lamp" position={[4.08, 1.01, 2.78]} rotation={[-0.27, 0.6, 1.93]}>
            <T.Group name="Lamp001" />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group name="Sketchfab_model002" position={[-0.35, 0, -0.6]} rotation={[-Math.PI / 2, 0, 0.52]} scale={0.14}>
        <T.Group name="toriifbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <T.Group name="RootNode001">
            <T.Group name="Balken_Mitte" scale={70}>
              <T.Mesh
                name="Balken_Mitte_Material_0"
                geometry={gltf.nodes.Balken_Mitte_Material_0.geometry}
                material={gltf.materials['Material.004']}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group name="Sketchfab_model003" position={[0.48, 0, -0.04]} rotation={[-Math.PI / 2, 0, 1.62]} scale={0.01}>
        <T.Group name="Lanternobjcleanermaterialmergergles">
          <T.Mesh
            name="Object_2"
            geometry={gltf.nodes.Object_2.geometry}
            material={gltf.materials.Lanternlambert7SG}
            position={[-6.64, -21.73, 3.2]}
          />
          <T.Mesh
            name="Object_2003"
            geometry={gltf.nodes.Object_2003.geometry}
            material={gltf.materials.Lanternlambert7SG}
            position={[-37.5, -20.53, -0.25]}
          />
        </T.Group>
      </T.Group>
      <T.Group name="Sketchfab_model004" position={[-0.56, 0, 0.12]} rotation={[-Math.PI / 2, 0, -2.97]} scale={0.01}>
        <T.Group name="Lanternobjcleanermaterialmergergles001">
          <T.Mesh
            name="Object_2001"
            geometry={gltf.nodes.Object_2001.geometry}
            material={gltf.materials.Lanternlambert7SG}
            position={[18.27, -7.76, 0.21]}
          />
        </T.Group>
      </T.Group>
      <T.Group name="Sketchfab_model005" position={[-0.27, 0, 0.69]} rotation={[-Math.PI / 2, 0, -2.97]} scale={0.01}>
        <T.Group name="Lanternobjcleanermaterialmergergles002">
          <T.Mesh
            name="Object_2002"
            geometry={gltf.nodes.Object_2002.geometry}
            material={gltf.materials.Lanternlambert7SG}
            position={[27.25, -17.63, -0.44]}
          />
          <T.Mesh
            name="Object_2004"
            geometry={gltf.nodes.Object_2004.geometry}
            material={gltf.materials.Lanternlambert7SG}
            position={[-1.18, 14.85, -0.44]}
          />
          <T.Mesh
            name="Object_2005"
            geometry={gltf.nodes.Object_2005.geometry}
            material={gltf.materials.Lanternlambert7SG}
            position={[-41.06, 18.98, -0.44]}
          />
        </T.Group>
      </T.Group>
      <T.Group name="Armature" position={[0.25, 0, 0.18]} rotation={[Math.PI / 2, 0, 0.5]} scale={0}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="ski_man"
          geometry={gltf.nodes.ski_man.geometry}
          material={gltf.materials.gradient}
          skeleton={gltf.nodes.ski_man.skeleton}
        />
      </T.Group>
      <T.Mesh name="Circle" geometry={gltf.nodes.Circle.geometry} material={gltf.materials['Material.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
